### PR TITLE
set shared libs off

### PR DESCRIPTION
**Pull request by ce1adon**

### CODE REVIEW

**Comment by pfultz2** [comment]
The`-DBUILD_SHARED_LIBS=Off` should be set in the requirements.txt file not in the cmake file.

**Comment by ce1adon** [comment]
> The`-DBUILD_SHARED_LIBS=Off` should be set in the requirements.txt file not in the cmake file.

Are they serving different functionalities?

**Comment by ce1adon** [comment]
@pfultz2 Any updates?

**Comment by pfultz2** [comment]
> Are they serving different functionalities?

Setting in the cmake will only make MIOpenTensile static(which we dont want). It wont make msgpack static. It needs to be set in the requirements.txt so it will build a msgpack static library.

**Comment by pfultz2** [comment]
I opened a PR with the fix.

**Pull request closed without merging**
